// <auto-generated />
namespace WEBAPI_Anuglar_CRUD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RenameDataTypeOfDepartmentCol : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameDataTypeOfDepartmentCol));
        
        string IMigrationMetadata.Id
        {
            get { return "202203301853242_RenameDataTypeOfDepartmentCol"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
